export type Icon = LucideIcon;

import {
  type LucideIcon,
  Anchor as LucideAnchorIcon,
  ArrowRight as LucideArrowRightIcon,
  Ban as LucideBanIcon,
  Banknote as LucideBanknoteIcon,
  Bell as LucideBellIcon,
  BookOpen as LucideBookOpenIcon,
  Building2 as LucideBuilding2Icon,
  Calendar as LucideCalendarIcon,
  ChartCandlestick as LucideChartCandlestickIcon,
  CheckCheck as LucideCheckCheckIcon,
  CheckCircle2 as LucideCheckCircle2Icon,
  CheckCircle as LucideCheckCircleIcon,
  Check as LucideCheckIcon,
  ChevronDown as LucideChevronDownIcon,
  ChevronLeft as LucideChevronLeftIcon,
  ChevronRight as LucideChevronRightIcon,
  ChevronsUpDown as LucideChevronsUpDownIcon,
  ChevronUp as LucideChevronUpIcon,
  CircleAlert as LucideCircleAlertIcon,
  CircleFadingArrowUp as LucideCircleFadingArrowUpIcon,
  CircleHelp as LucideCircleHelpIcon,
  Clock as LucideClockIcon,
  Cog as LucideCogIcon,
  Coins as LucideCoinsIcon,
  Container as LucideContainerIcon,
  Cookie as LucideCookieIcon,
  Cuboid as LucideCuboidIcon,
  CreditCard as LucideCreditCardIcon,
  DownloadCloud as LucideDownloadCloudIcon,
  Download as LucideDownloadIcon,
  Eye as LucideEyeIcon,
  EyeOff as LucideEyeOffIcon,
  FileClock as LucideFileClockIcon,
  FileUser as LucideFileUserIcon,
  FileDown as LucideFileDownIcon,
  File as LucideFileIcon,
  FileArchive as LucideFileArchiveIcon,
  FilePlus as LucideFilePlusIcon,
  FileSpreadsheet as LucideFileSpreadsheetIcon,
  FileText as LucideFileTextIcon,
  Filter as LucideFilterIcon,
  FolderTree as LucideFolderTreeIcon,
  GitBranch as LucideGitBranchIcon,
  Globe as LucideGlobeIcon,
  Handshake as LucideHandshakeIcon,
  HelpCircle as LucideHelpCircleIcon,
  Hash as LucideHashIcon,
  History as LucideHistoryIcon,
  Home as LucideHomeIcon,
  Image as LucideImageIcon,
  Info as LucideInfoIcon,
  Landmark as LucideLandmarkIcon,
  Layers as LucideLayersIcon,
  LayoutDashboard as LucideLayoutDashboardIcon,
  LayoutGrid as LucideLayoutGridIcon,
  Library as LucideLibraryIcon,
  Loader2 as LucideLoader2Icon,
  Lock as LucideLockIcon,
  Mail as LucideMailIcon,
  MessageSquare as LucideMessageSquareIcon,
  MessageCircleMore as LucideMessageCircleMoreIcon,
  MessageSquarePlus as LucideMessageSquarePlusIcon,
  MoreHorizontal as LucideMoreHorizontalIcon,
  PackageCheck as LucidePackageCheckIcon,
  Package as LucidePackageIcon,
  Paperclip as LucidePaperclipIcon,
  Pen as LucidePenIcon,
  Phone as LucidePhoneIcon,
  Play as LucidePlayIcon,
  Plus as LucidePlusIcon,
  PlusSquare as LucidePlusSquareIcon,
  RefreshCw as LucideRefreshCwIcon,
  RotateCw as LucideRotateCwIcon,
  Save as LucideSaveIcon,
  Search as LucideSearchIcon,
  Send as LucideSendIcon,
  Settings as LucideSettingsIcon,
  ShieldCheck as LucideShieldCheckIcon,
  Shield as LucideShieldIcon,
  Ship as LucideShipIcon,
  ShoppingCart as LucideShoppingCartIcon,
  Sparkles as LucideSparklesIcon,
  ShieldAlert as LucideShieldAlertIcon,
  TicketPlus as LucideTicketPlusIcon,
  Trash as LucideTrashIcon,
  Truck as LucideTruckIcon,
  TruckElectric as LucideTruckElectricIcon,
  UserCircle as LucideUserCircleIcon,
  Maximize as LucideMaximizeIcon,
  Minimize as LucideMinimizeIcon,
  ExternalLink as LucideExternalLinkIcon,
  UserCog as LucideUserCogIcon,
  User as LucideUserIcon,
  UserPlus as LucideUserPlusIcon,
  Users as LucideUsersIcon,
  Utensils as LucideUtensilsIcon,
  XCircle as LucideXCircleIcon,
  CircleGauge as LucideCircleGaugeIcon,
  RotateCcw as LucideRotateCcwIcon,
  AlertTriangle as LucideAlertTriangleIcon,
  MapPin as LucideMapPinIcon,
  ListTodo as LucideListTodoIcon,
  X as LucideXIcon,
  Activity as LucideActivityIcon,
  ParkingCircle as LucideParkingCircleIcon,
  Zap as LucideZapIcon,
  Trophy as LucideTrophyIcon,
  Settings2 as LucideSettings2Icon,
  PlayCircle as LucidePlayCircleIcon,
  Upload as LucideUploadIcon,
} from "lucide-react";

export const Icons = {
  Upload: LucideUploadIcon,
  Download: LucideDownloadIcon,
  Anchor: LucideAnchorIcon,
  Plus: LucidePlusIcon,
  ChevronRight: LucideChevronRightIcon,
  ChevronDown: LucideChevronDownIcon,
  ChevronUp: LucideChevronUpIcon,
  ChevronLeft: LucideChevronLeftIcon,
  ChevronsUpDown: LucideChevronsUpDownIcon,
  Check: LucideCheckIcon,
  Loader2: LucideLoader2Icon,
  UserCircle: LucideUserCircleIcon,
  Building2: LucideBuilding2Icon,
  LayoutDashboard: LucideLayoutDashboardIcon,
  Mail: LucideMailIcon,
  MapPin: LucideMapPinIcon,
  Settings: LucideSettingsIcon,
  CreditCard: LucideCreditCardIcon,
  HelpCircle: LucideHelpCircleIcon,
  Package: LucidePackageIcon,
  Utensils: LucideUtensilsIcon,
  FolderTree: LucideFolderTreeIcon,
  ShoppingCart: LucideShoppingCartIcon,
  Cog: LucideCogIcon,
  RotateCcw: LucideRotateCcwIcon,
  Eye: LucideEyeIcon,
  EyeOff: LucideEyeOffIcon,
  Search: LucideSearchIcon,
  Clock: LucideClockIcon,
  Container: LucideContainerIcon,
  Globe: LucideGlobeIcon,
  Handshake: LucideHandshakeIcon,
  Hash: LucideHashIcon,
  X: LucideXIcon,
  CircleAlert: LucideCircleAlertIcon,
  CircleGauge: LucideCircleGaugeIcon,
  ShieldCheck: LucideShieldCheckIcon,
  ShieldAlert: LucideShieldAlertIcon,
  ExternalLink: LucideExternalLinkIcon,
  TicketPlus: LucideTicketPlusIcon,
  BookOpen: LucideBookOpenIcon,
  MessageSquare: LucideMessageSquareIcon,
  MessageSquarePlus: LucideMessageSquarePlusIcon,
  MessageCircleMore: LucideMessageCircleMoreIcon,
  MoreHorizontal: LucideMoreHorizontalIcon,
  Pen: LucidePenIcon,
  Users: LucideUsersIcon,
  UserCog: LucideUserCogIcon,
  Shield: LucideShieldIcon,
  Trash: LucideTrashIcon,
  Truck: LucideTruckIcon,
  TruckElectric: LucideTruckElectricIcon,
  FileText: LucideFileTextIcon,
  Play: LucidePlayIcon,
  CheckCircle: LucideCheckCircleIcon,
  PackageCheck: LucidePackageCheckIcon,
  RefreshCw: LucideRefreshCwIcon,
  RotateCw: LucideRotateCwIcon,
  PlayCircle: LucidePlayCircleIcon,
  Save: LucideSaveIcon,
  Lock: LucideLockIcon,
  FilePlus: LucideFilePlusIcon,
  FileArchive: LucideFileArchiveIcon,
  Ban: LucideBanIcon,
  CircleHelp: LucideCircleHelpIcon,
  CheckCheck: LucideCheckCheckIcon,
  Cuboid: LucideCuboidIcon,
  Send: LucideSendIcon,
  History: LucideHistoryIcon,
  Home: LucideHomeIcon,
  FileClock: LucideFileClockIcon,
  Paperclip: LucidePaperclipIcon,
  File: LucideFileIcon,
  FileUser: LucideFileUserIcon,
  Image: LucideImageIcon,
  XCircle: LucideXCircleIcon,
  CheckCircle2: LucideCheckCircle2Icon,
  AlertTriangle: LucideAlertTriangleIcon,
  Calendar: LucideCalendarIcon,
  Landmark: LucideLandmarkIcon,
  Library: LucideLibraryIcon,
  Banknote: LucideBanknoteIcon,
  Layers: LucideLayersIcon,
  Coins: LucideCoinsIcon,
  FileSpreadsheet: LucideFileSpreadsheetIcon,
  DownloadCloud: LucideDownloadCloudIcon,
  ChartCandlestick: LucideChartCandlestickIcon,
  LayoutGrid: LucideLayoutGridIcon,
  FileDown: LucideFileDownIcon,
  Bell: LucideBellIcon,
  CircleFadingArrowUp: LucideCircleFadingArrowUpIcon,
  Sparkles: LucideSparklesIcon,
  Cookie: LucideCookieIcon,
  Info: LucideInfoIcon,
  Filter: LucideFilterIcon,
  GitBranch: LucideGitBranchIcon,
  ArrowRight: LucideArrowRightIcon,
  User: LucideUserIcon,
  UserPlus: LucideUserPlusIcon,
  Maximize: LucideMaximizeIcon,
  Minimize: LucideMinimizeIcon,
  Ship: LucideShipIcon,
  Phone: LucidePhoneIcon,
  ListTodo: LucideListTodoIcon,
  PlusSquare: LucidePlusSquareIcon,
  Activity: LucideActivityIcon,
  ParkingCircle: LucideParkingCircleIcon,
  Zap: LucideZapIcon,
  Trophy: LucideTrophyIcon,
  Settings2: LucideSettings2Icon,
};
